version: '3'
volumes:
  polynote-notebooks:
services:
  polynote:
    image: xtreamsrl/polynote-docker
    environment:
      POLYNOTE_CONFIG: |
        listen:
          host: 0.0.0.0
          port: 8192
    ports:
      - "8192:8192"
    volumes:
      - ./data:/data
      - polynote-notebooks:/usr/src/app/polynote/notebooks
    container_name: polynote
